services:
  - type: web
    name: naira-detection-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_PATH
        value: models/best.pt
      - key: DATA_YAML
        value: data/processed/data.yaml
      - key: CONF_THRESHOLD
        value: "0.5"
